"""
This module contains the agent API. This module should be extended to support additional GitHub events.
"""

import os
from anthropic import AsyncAnthropic, HUMAN_PROMPT, AI_PROMPT


async def get_completion(prompt: str, model: str = "claude-instant-1") -> str:
    """
    This function generates a completion from a given prompt using the specified model.

    Parameters:
    prompt (str): The prompt to generate a completion from.
    model (str, optional): The model to use for generating the completion. Defaults to "claude-instant-1".

    Returns:
    str: The generated completion.
    """
    if model.lower().strip() == "claude-instant-1":
        anthropic = AsyncAnthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
        completion = await anthropic.completions.create(
            model="claude-instant-1",  # claude-2 potentially causing a timeout bc it's too slow
            max_tokens_to_sample=300,
            prompt=prompt,
        )
        return completion.completion
    else:
        raise ValueError(f"Model {model} not supported.")


async def review_pull_request(filename: str, patch: str) -> str:
    """
    This function takes a filename and a patch as input and returns a completion generated by the Anthropic AI model.

    Parameters:
    filename (str): The name of the file in the pull request.
    patch (str): The changes made to the file in the pull request.

    Returns:
    str: The AI model's feedback on the pull request.
    """
    prompt = f"""
    {HUMAN_PROMPT} 
    You are reviewing a pull request. Given the following file and patch, provide detailed feedback on how to improve the code.
    filename: {filename}
    patch:\n{patch}
    {AI_PROMPT}
    """
    return await get_completion(prompt)
